quarkus:
  http:
    port: 8080
    read-timeout: 30m
    enable-compression: true
    limits:
      max-body-size: 500M
  package:
    type: uber-jar
  application:
    name: "Indy"
  resteasy:
    gzip:
      enabled: true
      max-input: 64M
  keycloak:
    devservices:
      enabled: false
  log:
    level: INFO
    min-level: TRACE
    category:
      "org.jboss":
        level: WARN
      "org.apache.http":
        level: ERROR
      "io.quarkus":
        level: WARN
      "io.smallrye":
        level: WARN
      "org.eclipse":
        level: WARN
      "io.netty":
        level: WARN
      "io.grpc":
        level: WARN
      "org.commonjava.indy.service":
        level: TRACE
    console:
      enable: true
      level: DEBUG
    file:
      level: DEBUG
      enable: true
      path: "log/indy-ui-service.log"
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-backup-index: 5
        max-file-size: 10M
  swagger-ui:
    always-include: true
    title: "Indy"
  opentelemetry:
    enabled: false

  quinoa:
    # ui-dir: "webui"
    build-dir: "dist"
    package-manager-install:
      ~: true
      node-version: "18.12.1"
      npm-version: "9.4.0"
    package-manager-command:
      install-env:
        strict-ssl: false
      install: "npm config set strict-ssl false && npm ci"

# These REST APIs are not needed to show in rest docs
mp:
  openapi:
    scan:
      exclude:
        packages:
          - org.commonjava.indy.service.ui.jaxrs.stats
          - org.commonjava.indy.service.ui.models.stats
          - org.commonjava.indy.service.ui.keycloak



indy_security:
  enabled: False


## [rest client]
service-api/mp-rest/uri: http://localhost:8080/
service-api/mp-rest/scope: javax.inject.Singleton
service-api/mp-rest/connectTimeout: 60000
service-api/mp-rest/readTimeout: 60000
#service-api/mp-rest/providers: org.commonjava.indy.service.ui.client.AuthClientRequestFilter

"%dev":
  quarkus:
    log:
      level: TRACE
      min-level: TRACE
      category:
        "org.jboss":
          level: INFO
        "org.apache.http":
          level: ERROR
        "io.quarkus":
          level: INFO
        "io.smallrye":
          level: INFO
        "org.eclipse":
          level: INFO
        "io.netty":
          level: INFO
        "io.grpc":
          level: INFO
        "org.commonjava.indy.service":
          level: TRACE
      console:
        enable: true
      file:
        enable: true
        path: "/tmp/indy-ui-service.log"
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        rotation:
          max-backup-index: 5
          max-file-size: 10M
    quinoa:
      package-manager-command:
        install: "npm config set strict-ssl false && npm ci"
